[server]
host = "localhost"
port = 5600

[awatcher]
idle-timeout-seconds = 120
poll-time-idle-seconds = 5
poll-time-window-seconds = 1

[[awatcher.filters]]
match-app-id = "Spotify"
replace-app-id = "Spotify"

[[awatcher.filters]]
match-app-id = "org.pwmt.zathura"
replace-app-id = "Zathura"

[[awatcher.filters]]
match-app-id = "Brave-browser"
replace-title = "Brave"

[[awatcher.filters]]
match-app-id = "org.telegram.desktop"
replace-title = "Telegram"

[[awatcher.filters]]
match-app-id = "Logseq"
replace-title = "Logseq"

[[awatcher.filters]]
match-app-id = "firefox"
replace-title = "Firefox"

[[awatcher.filters]]
match-app-id = "anki"
replace-title = "Anki"

[[awatcher.filters]]
match-app-id = "kitty"
replace-title = "kitty"

[[awatcher.filters]]
match-app-id = "zoom"
replace-app-id = "Zoom"
