env:
  TERM: xterm-256color

window:
  title: Alacritty
  dynamic_padding: false
  decorations: "None"
  opacity: 1
  padding:
    x: 0
    y: 2

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5000
  auto_scroll: true

tabspaces: 4
live_config_reload: true
alt_send_esc: true
dynamic_title: false
draw_bold_text_with_bright_colors: true

cursor:
  # ▇ Block
  # _ Underline
  # | Beam
  style: Underline
  unfocused_hollow: true

font:
  size: 12.0
  normal:
    family: JetBrains Mono
    style: Regular
  bold:
    family: JetBrains Mono
    style: Bold
  italic:
    family: JetBrains Mono
    style: Italic
  bold_italic:
    family: JetBrains Mono
    style: Bold Italic
  offset:
    x: 0
    y: 1

schemes:
  kanagawa: &kanagawa
    primary:
      background: "#1f1f28"
      foreground: '#dcd7ba'
    selection:
      background: '0x2d4f67'
      foreground: '0xc8c093'
    normal:
      black:   '0x090618'
      red:     '0xc34043'
      green:   '0x76946a'
      yellow:  '0xc0a36e'
      blue:    '0x7e9cd8'
      magenta: '0x957fb8'
      cyan:    '0x6a9589'
      white:   '0xc8c093'
    bright:
      black:   '0x727169'
      red:     '0xe82424'
      green:   '0x98bb6c'
      yellow:  '0xe6c384'
      blue:    '0x7fb4ca'
      magenta: '0x938aa9'
      cyan:    '0x7aa89f'
      white:   '0xdcd7ba'

colors: *kanagawa

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: Key0, mods: Control, action: ResetFontSize }
  - { key: Plus, mods: Control, action: IncreaseFontSize }
  - { key: Minus, mods: Control, action: DecreaseFontSize }
  - { key: F11, mods: None, action: ToggleFullscreen }
