add_newline = false

[cmd_duration]
disabled = true

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[golang]
symbol = " "

[rust]
symbol = " "

[elm]
symbol = " "

[lua]
symbol = " "
lua_binary = "luajit"

[battery]
disabled = true
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[directory]
truncation_length = 5
truncate_to_repo = false
