add_newline = false

[nodejs]
symbol = "Node "

[python]
symbol = "Py "

[elm]
symbol = "Elm "

[lua]
symbol = "Lua "
lua_binary = "luajit"

[rust]
symbol = "Rust "

[package]
symbol = "PKG "

[battery]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 5
truncate_to_repo = false
