reset_count = "/home/olex/.resets"
npause_focus = true
poll_rate = 100
play_res = "1920x1080+0,0"
alt_res = "400x1080+810,0"
[delay]
wp_pause = 20
idle_pause = 20
unpause = 20
stretch = 20
ghost_pie_fix = 20
warp = 0

[hooks]
reset = ""
alt_res = ""
normal_res = ""
wall_lock = ""
wall_unlock = ""
wall_play = ""
wall_reset = ""

# ingame_focus            Focus active instance.
# ingame_reset            Reset active instance.
# ingame_toggle_res       Toggle the resolution for active instance.
# wall_focus              Focus wall projector.
# wall_reset_all          Reset all unlocked instances.
# wall_lock               Lock hovered instance.
# wall_lock(n)            Lock instance N.
# wall_play               Play hovered instance.
# wall_play(n)            Play instance N.
# wall_reset              Reset hovered instance.
# wall_reset(n)           Reset instance N.
# wall_reset_others       Focus reset hovered instance.
# wall_reset_others(n)    Focus reset instance N.
# wall_play_first_locked  Plays the first locked and idle instance.
[keybinds]
"y"             = ["wall_reset_all", "ingame_reset"]
"Shift-y"       = ["wall_play_first_locked"]
"Alt-y" = ["wall_focus"]
"Ctrl-LMB"      = ["wall_play"]
"LMB"           = ["wall_lock"]
"RMB"           = ["wall_reset"]

[obs]
enabled = true
port = 4455
password = ""

[wall]
enabled = true
confine_pointer = false
goto_locked = true
reset_unlock = true
grace_period = 250

# The resolution to set your instances to while they are on the wall, in
# the format "W,H+X,Y" (e.g. 960x360+0,0). Delete or comment out to disable
# instance stretching.
stretch_res = "960x360+0,0"

use_f1 = false

# The percentage to show freeze at on preview. Set to 0 or below to disable.
freeze_at = 5
show_at = 5

[wall.performance]
sleepbg_path = ""
affinity = "sequence"

[wall.performance.sequence]
# The number of CPUs to give to the active instance. Set to 0 to disable.
active_cpus = 3
# The number of CPUs to give to instances in the background. Set to 0 to disable.
background_cpus = 5

# The number of CPUs to give to locked instances. Set to 0 to disable.
lock_cpus = 2

[wall.performance.advanced]
# How many groups to subdivide affinity groups into. Set this to the number of CCXs your CPU has. If you don't know what this means, leave it at 1.
ccx_split = 1

# The number of CPUs (cores, or threads if you have SMT) to allocate to each affinity group.
# - Idle        Instances which have finished generating a world.
# - Low         Instances which are on preview and have crossed low_threshold.
# - Mid         Instances which have not crossed low_threshold and while the user is not on the wall.
# - High        Instances which have not crossed low_threshold and while the user is on the wall.
# - Active      The instance being played by the user.
affinity_idle = 2
affinity_low = 4
affinity_mid = 6
affinity_high = 8
affinity_active = 8

# If enabled (n > 0), instances will remain in the mid affinity group for this
# many milliseconds after finishing generating. This gives extra CPU time to
# allow for chunks to load in faster.
burst_length = 0

# The world generation percentage at which instances are moved from the high
# group to the low group.
low_threshold = 20
