confirmOnQuit: false
disableStartupPopups: true
notARepository: "skip"
promptToReturnFromSubprocess: true
gui:
  scrollHeight: 8
  scrollPastBottom: false
  sidePanelWidth: .28
  expandFocusedSidePanel: true
  mainPanelSplitMode: "flexible"
  language: "en"
  timeFormat: "02 Jan 06 15:04 MST" # https://pkg.go.dev/time#Time.Format
  skipDiscardChangeWarning: false
  skipStashWarning: false
  showFileTree: false
  showListFooter: false
  showRandomTip: false
  showBottomLine: false
  showCommandLog: true
  nerdFontsVersion: "3"
git:
  autoFetch: true
  autoRefresh: true
  parseEmoji: true
keybinding:
  universal:
    jumpToBlock: ["5", "1", "2", "3", "4"]
