[tools]
usage = "latest" # required for mise to work
bun = "latest"
node = "20.13"
gleam = "latest"
rebar = "latest"
go = "latest"
golangci-lint = "latest"

[settings]
go_set_goroot = false
go_set_gopath = false
experimental = true
