[tools]
usage = "latest" # required for mise to work
bun = "latest"
gleam = "latest"
rebar = "latest"
go = "latest"
golangci-lint = "latest"
deno = "latest"
node = "lts"

[settings]
go_set_goroot = false
go_set_gopath = false
experimental = true
