[tools]
usage = "latest"
bun = "latest"
gleam = "latest"
rebar = "latest"
go = "latest"
golangci-lint = "latest"
deno = "latest"
node = "lts"
shellcheck = "latest"
shfmt = "latest"

[settings]
experimental = true
go_set_goroot = false
go_set_gopath = false
